/* Generated by            cobc 1.1.0 */
/* Generated from          test.cbl */
/* Generated at            Jan 13 2017 10:54:41 PHT */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C test.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"test.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "test.c.h"

/* Function prototypes */

int YOUR__PROGRAM__NAME (void);
static int YOUR__PROGRAM__NAME_ (const int);

/* Functions */

int
YOUR__PROGRAM__NAME ()
{
  return YOUR__PROGRAM__NAME_ (0);
}

static int
YOUR__PROGRAM__NAME_ (const int entry)
{
  /* Local variables */
  #include "test.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      if (module.next)
        cob_set_cancel ((const char *)"YOUR-PROGRAM-NAME", (void *)YOUR__PROGRAM__NAME, (void *)YOUR__PROGRAM__NAME_);
      (*(int *) (b_1)) = 0;
      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry YOUR-PROGRAM-NAME */

  l_2:;

  /* MAIN SECTION */

  /* MAIN-PROCEDURE */

  /* test.cbl:14: DISPLAY */
  {
    cob_display (0, 1, 1, &c_1);
  }
  /* test.cbl:15: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));
}

/* End functions */

