/* Generated by            cobc 1.1.0 */
/* Generated from          test.cbl */
/* Generated at            Jan 13 2017 10:54:41 PHT */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C test.cbl */


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

